## For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html
#
# Specifies the JVM arguments used for the daemon process.
# The setting is particularly useful for tweaking memory settings.
# Default value: -Xmx1024m -XX:MaxPermSize=256m
# org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
#
# When configured, Gradle will run in incubating parallel mode.
# This option should only be used with decoupled projects. More details, visit
# http://www.gradle.org/docs/current/userguide/multi_project_builds.html#sec:decoupled_projects
# org.gradle.parallel=true
#Thu Mar 26 16:33:19 EAT 2020
android.enableJetifier=true
android.nonFinalResIds=false
org.gradle.jvmargs=-Xmx2g -Dkotlin.daemon.jvm.options=-Xmx2g --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.management/sun.management=ALL-UNNAMED --add-opens=jdk.management/com.sun.management.internal=ALL-UNNAMED --add-opens=java.base/jdk.internal.reflect=ALL-UNNAMED --add-exports=java.base/jdk.internal.reflect=ALL-UNNAMED

# If your Gradle daemon is not using JDK 17, set the path below to your local JDK 17 installation
# Example (Windows): org.gradle.java.home=C:\\Program Files\\Microsoft\\jdk-17.0.10.7-hotspot
# org.gradle.java.home=C:\\Path\\To\\Your\\JDK17
android.useAndroidX=true
android.sdkDownload=false
android.builder.sdkDownload=false
android.ndkVersion=26.2.11394342

# Coordinates & metadata for publishing
GROUP=org.smartregister
VERSION_NAME=2.0.0
VERSION_CODE=3
POM_SETTING_NAME=ECAP CHW Core
POM_SETTING_ARTIFACT_ID=opensrp-client-ecap-chw-core
POM_SETTING_PACKAGING=aar
POM_SETTING_DESCRIPTION=A module of OPENSRP CHW-Core library that holds common CHW-based functionalities
POM_SETTING_URL=https://github.com/BlueCodeSystems/opensrp-client-ecap-chw-core
POM_SETTING_SCM_URL=https://github.com/BlueCodeSystems/opensrp-client-ecap-chw-core
POM_SETTING_SCM_CONNECTION=scm:git@github.com:BlueCodeSystems/opensrp-client-ecap-chw-core
POM_SETTING_SCM_DEV_CONNECTION=scm:git@github.com:BlueCodeSystems/opensrp-client-ecap-chw-core.git
POM_SETTING_LICENCE_NAME=The Apache Software License, Version 2.0
POM_SETTING_LICENCE_URL=http://www.apache.org/licenses/LICENSE-2.0.txt
POM_SETTING_LICENCE_DIST=repo
POM_SETTING_DEVELOPER_ID=BlueCodeSystems
POM_SETTING_DEVELOPER_NAME=BlueCode Systems

# Optional Sonatype creds (or pass via -P or env)
# sonatypeUsername=
# sonatypePassword=

# Keep Gradle simple to avoid worker serialization edge-cases
org.gradle.workers.max=1
org.gradle.parallel=false
org.gradle.configuration-cache=false
